### PR TITLE
chore: support for Swift

### PR DESCRIPTION
**Pull request by giautm**
Added support for Swift, I need this modified to use `react-native-branch` in the config plugin.

See https://github.com/expo/config-plugins/pull/28

cc: @Kudo from the Expo team

### CODE REVIEW

**Comment by giautm** [comment]
@jdee, sorry for tagging. But, can you review this PR please?

**Comment by echo-branch** [comment]
@gdeluna-branch 
Will be handling maintenance. 

Just to note, in the past we did not support expo due to missing early lifecycle calls that could only be solved by ejecting the project.

**Comment by giautm** [comment]
Hi @echo-branch, I developed an Expo config plugin to allow users to use react-native-branch with Expo EAS Build in [this PR](https://github.com/expo/config-plugins/pull/28). If your team allows, I can create another PR to transfer that plugin to this repository.

**Comment by giautm** [comment]
Hi @gdeluna-branch , Can you review my PR please?

**Comment by gdeluna-branch** [comment]
Apologies for the delay, I'll be reviewing this towards the end of next week.

**Comment by giautm** [comment]
> Apologies for the delay, I'll be reviewing this towards the end of next week.

Thanks very much. Please also feedback on accepting the new plugin configuration.

**Comment by gdeluna-branch** [comment]
Will also take a look. Thanks

**Comment by gdeluna-branch** [comment]
Will publish this early next week. Thanks for you patience.

**Comment by gdeluna-branch** [comment]
This change has been released here:
https://www.npmjs.com/package/react-native-branch/v/5.3.0
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases/tag/v5.3.0

Please create a new issue if something is incorrect.

Thanks.

**Pull request merged**
