### PR TITLE
Fix removeListener deprecate warning

### PR DESCRIPTION
**Pull request by addingama**

### CODE REVIEW

**Comment by flogy** [comment]
Thanks for the fix, will add it via [patch-package](https://www.npmjs.com/package/patch-package) for now. Can this be merged?

**Review by markmoomoo — APPROVED** [review]
thanks for fix it, the warning is annoying

**Comment by ensargunesdogdu** [comment]
Could you please merge this? It's really annoying.

**Comment by gdeluna-branch** [comment]
I'll be reviewing this and the other pending PRs soon. Sorry for the delay.

**Comment by gdeluna-branch** [comment]
This change has been released here:
https://www.npmjs.com/package/react-native-branch/v/5.3.0
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases/tag/v5.3.0

Please create a new issue if something is incorrect.

Thanks.

**Comment by ilyagru** [comment]
I think you forgot to add checks against `null`. There are situations when `.remove()` can be called on `null`.

**Comment by ilyagru** [comment]
It would be great to merge this one #694 pretty soon - PR created, thanks!

**Comment by ilyagru** [comment]
It would be great to merge this one #694 pretty soon - PR created, thanks! @gdeluna-branch

**Comment by ilyagru** [comment]
It would be great to merge this one #694 pretty soon - PR created, thanks! @gdeluna-branch @markmoomoo

**Pull request merged**
